### ISSUE TITLE
When is this going to be in chrome

### ISSUE THREAD

**Issue by codingedgar** [Kaiido/roundRect#1]
Thank your for your polyfill 👏💛

According to this: https://stackoverflow.com/a/68359160/9130688 there is https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-roundrect available in some versions of chrome, but it does not seem to exist in the current version of chrome yet, do you know of a source to watch where it will be available?

( i even added it to : https://github.com/Fyrd/caniuse/issues/6034)

**Comment by Kaiido** [comment]
Thanks,
Chrome still hides it under the Experimental Web Platforms flag.  
I'm not sure when they plan to release it officially though...

**Comment by codingedgar** [comment]
Thank you, your polyfill works perfectly also 💛🤝
